Social-Media/Controllers/GroupController.cs
using Social_Media.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Social_Media.Models;

namespace Social_Media.Controllers
{
    public class GroupController : Controller
    {
        public ActionResult CreateGroup()
        {
            Group g = new Group();
            MyDbcontext db = new MyDbcontext();
            var users = db.Users.ToList();
            ViewBag.data = users;
            return View(users);
        }
        [HttpGet]
        // GET: Group
        [Route("Group/AddMembers/{id}")]
        public ActionResult AddMembers(int id, String group_name, String desc)
        {
            Group g = new Group();
            MyDbcontext db = new MyDbcontext();
            var users = db.Users.ToList();
            ViewBag.data = users;
            g.GroupName = group_name;
            g.Description = desc;
            Console.WriteLine(group_name);
            db.Group.Add(g);
            db.SaveChanges();
            //
            var firstIDS = db.RelationShips.Where(x => x.Status == 3 && x.Friend.UserID == 9).Select(l => l.Mate.UserID).ToList();
            var secIDS = db.RelationShips.Where(x => x.Status == 3 && x.Mate.UserID == 9).Select(l => l.Friend.UserID).ToList();
            List<User> res = new List<User>();
            foreach (var U in secIDS)
            {
                User ID = db.Users.Where(x => x.UserID == U).Single();
                res.Add(ID);
            }
            foreach (var U in firstIDS)
            {
                User ID = db.Users.Where(x => x.UserID == U).Single();
                res.Add(ID);
            }
            var username = Session["Username"];
            User tmp = new User();
            tmp = db.Users.Where(x => x.Username == username.ToString()).Single();
            var userid = tmp.UserID;
            AddMember(id, userid);
            return View(res);
        }

        [HttpGet]
        public void AddMember(int groupid, int MemberID)
        {

            MyDbcontext db = new MyDbcontext();
            Group update = new Group();
            update = db.Group.Where(x => x.GroupID == groupid).Single();
            update.Users.Add(db.Users.Where(x => x.UserID == MemberID).Single());
            db.Group.Attach(update);
            db.Entry(update).Collection(x => x.Users).IsLoaded = true;
            db.SaveChanges();

        }

        [HttpGet]
        public void RemoveMember(int groupid, int MemberID)
        {
            MyDbcontext db = new MyDbcontext();
            Group update = new Group();
            update = db.Group.Where(x => x.GroupID == groupid).Single();
            update.Users.Remove(db.Users.Where(x => x.UserID == MemberID).Single());
            db.Group.Attach(update);
            db.Entry(update).Collection(x => x.Users).IsLoaded = true;
            db.SaveChanges();

        }
        [Route("Group/Group/{id}")]
        public ActionResult Group(int id)
        {
            MyDbcontext db = new MyDbcontext();
            var username = Session["Username"];
            User user = new User();
            user = db.Users.Where(u => u.Username == username.ToString()).FirstOrDefault();
            var firstIDS = db.Users.Where(x => x.UserID == x.UserID).ToList();
            var secIDS = db.Users.Where(x => x.UserID == x.UserID).ToList();
            List<Post> fposts = new List<Post>();

            foreach (var data in secIDS)
                firstIDS.Add(data);
            foreach (var data in firstIDS)
            {
                var friendpost = db.Posts.Where(x => x.UserID == data.UserID).ToList();
                fposts.AddRange(friendpost);
            }
            var post = db.Posts.Where(x => x.GroupID == id).ToList();
            List<CommentsModel> showposts = new List<CommentsModel>();
            foreach (var pos in post)
            {
                var commentss = db.Comment.Where(x => x.PostID == pos.ID).ToList();
                showposts.Add(new CommentsModel { Comments = commentss, post = pos });
            }
            ProfileModel profile = new ProfileModel { Friends = firstIDS, LoggedUser = user, Posts = showposts, FriendPosts = showposts };
            return View(profile);
        }
        [Route("Group/Members/{id}")]
        public ActionResult Members(int id)
        {
            MyDbcontext db = new MyDbcontext();
            var members = db.Group.Where(x => x.GroupID == id).Select(u => u.Users).SingleOrDefault().ToList();
            return View(members);
        }
        [Route("Group/DeleteGroup/{id}")]
        public ActionResult DeleteGroup(int id)
        {
            MyDbcontext db = new MyDbcontext();
            Group update = new Group();
            update = db.Group.Where(x => x.GroupID == id).Single();
            db.Group.Remove(update);
            db.SaveChanges();
            return RedirectToAction("index", "Home");
        }
        public ActionResult LeaveGroup(int groupid, int MemberID)
        {
            MyDbcontext db = new MyDbcontext();
            Group update = new Group();
            update = db.Group.Where(x => x.GroupID == groupid).Single();
            update.Users.Remove(db.Users.Where(x => x.UserID == MemberID).Single());
            db.Group.Attach(update);
            db.Entry(update).Collection(x => x.Users).IsLoaded = true;
            db.SaveChanges();
            return RedirectToAction("index", "Home");
        }

        public ActionResult Create(Post post, int id)
        {
            MyDbcontext db = new MyDbcontext();
            var username = Session["Username"];
            User user1 = new User();
            user1 = db.Users.Where(u => u.Username == username).FirstOrDefault();

            if (!ModelState.IsValid)
            {
                var posts = new Post();

                return View("Create", post);
            }

            if (post.ID == 0)

                post.like_post = 0;
            post.DateTime = DateTime.Now;
            post.UserID = (byte)user1.UserID;
            post.User = db.Users.FirstOrDefault(user => user.UserID == post.UserID);
            post.DateTime = DateTime.Now;
            post.GroupID = id;
            db.Posts.Add(post);
            db.SaveChanges();



            return RedirectToAction("Index", "Home");


        }

    }
}

Social-Media/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Social_Media.Models;
using Social_Media.ViewModel;
namespace Social_Media.Controllers
{
    public class HomeController : Controller
    {
        MyDbcontext db = new MyDbcontext();
        public ActionResult Index()
        {
            var username = Session["Username"];
            User user = new User();
            user = db.Users.Where(u => u.Username == username).FirstOrDefault();
            var firstIDS = db.RelationShips.Where(x => x.Status == 3 && x.Friend.Username == username).Select(l => l.Mate).ToList();
            var secIDS = db.RelationShips.Where(x => x.Status == 3 && x.Mate.Username == username).Select(l => l.Friend).ToList();
            List<Post> fposts = new List<Post>();

            foreach (var data in secIDS)
                firstIDS.Add(data);
            foreach (var data in firstIDS)
            {
                var friendpost = db.Posts.Where(x => x.UserID == data.UserID).ToList();
                fposts.AddRange(friendpost);
            }

            var post = db.Posts.Where(x => x.UserID == user.UserID).ToList();
            List<CommentsModel> showposts = new List<CommentsModel>();
            foreach (var pos in post)
            {
                var commentss = db.Comment.Where(x => x.PostID == pos.ID).ToList();
                showposts.Add(new CommentsModel { Comments = commentss, post = pos });
            }

            List<CommentsModel> showfriendsposts = new List<CommentsModel>();
            foreach (var pos in fposts)
            {
                var commentss = db.Comment.Where(x => x.PostID == pos.ID).ToList();
                showfriendsposts.Add(new CommentsModel { Comments = commentss, post = pos });
            }
            ProfileModel profile = new ProfileModel { Friends = firstIDS, LoggedUser = user, Posts = showposts, FriendPosts = showfriendsposts };
            return View(profile);
        }

        public ActionResult About()
        {

            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page. diaa ";

            return View();
        }
    }
}

Social-Media/Controllers/ProfileController.cs
using System.Linq;
using System.Web;
using System.IO;
using Social_Media.Models;
using Social_Media.ViewModel;
using System.Web.Mvc;
using WebMatrix.WebData;
using System.Collections.Generic;

namespace Social_Media.Controllers
{
    public class ProfileController : Controller
    {
        private MyDbcontext db = new MyDbcontext();
        public ActionResult ProfileTemp()
        {

            var username = Session["Username"];
            User user = new User();
          
            user = db.Users.Where(u => u.Username == username).FirstOrDefault();
            var post = db.Posts.Where(x => x.UserID == user.UserID).ToList();
            List<CommentsModel> showposts = new List<CommentsModel>();
            var firstIDS = db.RelationShips.Where(x => x.Status == 3 && x.Friend.Username == username).Select(l => l.Mate).ToList();
            var secIDS = db.RelationShips.Where(x => x.Status == 3 && x.Mate.Username == username).Select(l => l.Friend).ToList();
            foreach (var data in secIDS)
                firstIDS.Add(data);
           foreach(var pos in post)
            {
                var commentss = db.Comment.Where(x => x.PostID == pos.ID).ToList();
                showposts.Add(new CommentsModel { Comments = commentss, post = pos });
            }
            ProfileModel profile = new ProfileModel { Friends = firstIDS, LoggedUser = user, Posts = showposts };
            return View(profile);
        }
        // GET: Profile
        [HttpPost]
        public ActionResult UploadPic(HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var username = Session["Username"];
                    string path = Path.Combine(Server.MapPath("~/UploadedFiles"), file.FileName);
                    file.SaveAs(path);
                    db.Users.FirstOrDefault(u => u.Username == username).Pic = file.FileName;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("ProfileTemp");
        }
        [HttpPost]
        public ActionResult UploadCover(HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string path = Path.Combine(Server.MapPath("~/UploadedFiles"), file.FileName);
                    file.SaveAs(path);
                    var username = Session["Username"];
                    db.Users.FirstOrDefault(u => u.Username == username).Cover = file.FileName;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("ProfileTemp");
        }
        public void Block(int friendID)
        {
            var username = Session["Username"];
            int Relation = db.RelationShips.Where(x => ((x.Mate.UserID == friendID) && (x.Friend.Username == username)) || ((x.Friend.UserID == friendID) && (x.Mate.Username == username)))
                       .Select(l => l.RelationID).SingleOrDefault();
            RelationShip update = new RelationShip();
            update = db.RelationShips.Where(x => x.RelationID == Relation).Single();
            update.Status = 2;
            db.RelationShips.Attach(update);
            db.Entry(update).Property(x => x.Status).IsModified = true;
            db.Configuration.ValidateOnSaveEnabled = false;
            db.SaveChanges();
        }
        public ActionResult MoveToEditProfile()
        {
            return RedirectToAction("EditProfile");
        }
        public ActionResult EditProfile(ProfileModel profile)
        {

            return View(profile);
        }
        [HttpPost]
        public ActionResult EditInfo(Social_Media.Models.User userinfo)
        {
            if (ModelState.IsValid)
            {
                var username = Session["Username"];
                db.Users.FirstOrDefault(u => u.Username == username).Bio = userinfo.Bio;
                db.Users.FirstOrDefault(u => u.Username == username).Education = userinfo.Education;
                db.Users.FirstOrDefault(u => u.Username == username).Location = userinfo.Location;
                db.Users.FirstOrDefault(u => u.Username == username).Birthdate = userinfo.Birthdate;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                ViewBag.Message = "Info has been changed";

            }
            return RedirectToAction("ProfileTemp");
        }
        [HttpPost]
        public ActionResult ChangePassword(ProfileModel changePasswordModel)
        {
            if (ModelState.IsValid)
            {
                var username = Session["Username"];
                User user = db.Users.FirstOrDefault(u => u.Username == username);
                if (changePasswordModel.CurrentPassword == user.Password)
                {
                    db.Users.FirstOrDefault(u => u.Username == username).Password = changePasswordModel.NewPassword;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();
                    ViewBag.Message = "Password has been changed";
                }
                else
                {
                    ModelState.AddModelError("Error", "Old Password is not correct.");
                    return RedirectToAction("EditProfile");
                }

            }
            return RedirectToAction("ProfileTemp");
        }
        [HttpPost]
        public ActionResult DeactivateAccount(User userlog)
        {
            var username = Session["Username"];
            User user = db.Users.FirstOrDefault(x => x.Username == username);
            if (userlog.Email == user.Email && userlog.Password == user.Password)
            {
                db.Users.FirstOrDefault(x => x.Username == username).InActive = true;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                return RedirectToAction("login", "Account");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }
        public ActionResult Visit(int id)
        {
            User friend = db.Users.Find(id);
            SearchableModel relation = new SearchableModel();
            var username = Session["Username"];
            User user = db.Users.FirstOrDefault(x => x.Username == username);
            var rel = db.RelationShips.Where(x => (x.Friend.UserID == user.UserID && x.Mate.UserID == id) || (x.Friend.UserID == id && x.Mate.UserID == user.UserID)).Select(
                 x => new
                 {
                     actionuser = x.ActionUser.UserID,
                     state = x.Status,
                 }
                ).SingleOrDefault();
            if (rel != null)
            {
                if (rel.actionuser == id && rel.state == 1)
                    relation.RelationState = 4;
                else
                    relation.RelationState = rel.state;
            }
            else
                relation.RelationState = 0;
            var post = db.Posts.Where(x => x.UserID == friend.UserID).ToList();
            List<CommentsModel> showposts = new List<CommentsModel>();
            foreach (var pos in post)
            {
                var commentss = db.Comment.Where(x => x.PostID == pos.ID).ToList();
                showposts.Add(new CommentsModel { Comments = commentss, post = pos });
            }
            relation.ResultUser = friend;
            relation.FriendPosts = showposts;
            return View(relation);
        }
    }
}

Social-Media/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
@RenderPage("~/Views/Shared/_header.cshtml")

Social-Media/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Social-Media/Views/Home/Index.cshtml
@using Social_Media.Models
@model Social_Media.ViewModel.ProfileModel
@{
    ViewBag.Title = "Home Page";
}
@RenderPage("~/Views/Shared/_header.cshtml")

<main>
    <div class="main-section">
        <div class="container">
            <div class="main-section-data">
                <div class="row">
                    <div class="col-lg-3 col-md-4 pd-left-none no-pd">
                        <div class="main-left-sidebar no-margin">
                            <div class="user-data full-width">
                                <div class="user-profile">
                                    <div class="username-dt">
                                        <div class="usr-pic">
                                            @if (Model.LoggedUser.Pic == null)
                                            {
                                                <img src="http://via.placeholder.com/170x170" alt="">
                                            }
                                            else
                                            {
                                                <img src="~/UploadedFiles/@Html.DisplayFor(model=>model.LoggedUser.Pic)" alt="" style="width:120px;height:120px">
                                            }
                                        </div>
                                    </div><!--username-dt end-->
                                    <div class="user-specs">
                                        <h3>@Model.LoggedUser.Username</h3>
                                    </div>
                                </div><!--user-profile end-->
                                <ul class="user-fw-status">
                                    <li>
                                        <h4>Following</h4>
                                        <span>34</span>
                                    </li>
                                    <li>
                                        <h4>Followers</h4>
                                        <span>155</span>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("ProfileTemp","Profile")" title="">View Profile</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("CreateGroup","Group")" title="">Create Group</a>
                                    </li>
                                    <li>
                                        <h4>Your Groups</h4>
                                        @{
                                            MyDbcontext db = new MyDbcontext();
                                            var username = Session["Username"];
                                            User tmp = new User();
                                            tmp = db.Users.Where(x => x.Username == username.ToString()).Single();
                                            var userid = tmp.UserID;
                                            //var groups = db.Group.Where(x => x.Users.Contains(tmp)).ToList();
                                            var groups = db.Group.Where(x => x.Users.Any(m => m.UserID == tmp.UserID)).ToList();


                                            foreach (var group in groups)
                                            {
                                                <a href="@Url.Action("Group","Group",new { id = group.GroupID })">@group.GroupName</a><br /><br />
                                            }
                                        }
                                    </li>
                                </ul>
                            </div><!--user-data end-->
                        </div><!--main-left-sidebar end-->
                    </div>
                    <div class="col-lg-6 col-md-8 no-pd">
                        <div class="main-ws-sec">
                            <div class="post-topbar">
                                <div class="post-st">
                                    <ul>
                                        <li><a href="#" title="" onclick="NewPost()"> Create Post </a> </li>

                                    </ul>
                                </div><!--post-st end-->
                            </div><!--post-topbar end-->
                            <div class="posts-section">
                                <div class="modal fade" id="ShowModal">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <a href="#" class="close" data-dismiss="modal">&times;</a>
                                                <h4>New Post</h4>
                                            </div>
                                            <div class="modal-body">
                                                <form id="post">
                                                    <div class="form-group">
                                                        <div class="input-group">
                                                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                                            <input class="form-control" type="text" name="Body" id="body" placeholder="What's in your mind ... ?" />
                                                        </div>
                                                    </div>



                                                </form>
                                                <div class="form-group">
                                                    <button class="btn btn-info form-control" type="submit" onclick="SaveForm()"><i class="glyphicon glyphicon-registration-mark"></i> Post</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="post-bar">
                                    @{
                                        Html.RenderPartial("~/Views/Shared/Index.cshtml", Model.Posts);
                                        Html.RenderPartial("~/Views/Shared/Index.cshtml", Model.FriendPosts);
                                    }

                                </div><!--post-bar end-->
                                <div class="process-comm">
                                    <div class="spinner">
                                        <div class="bounce1"></div>
                                        <div class="bounce2"></div>
                                        <div class="bounce3"></div>
                                    </div>
                                </div><!--process-comm end-->
                            </div><!--posts-section end-->
                        </div><!--main-ws-sec end-->
                    </div>
                </div>
            </div><!-- main-section-data end-->
        </div>
    </div>
</main>

<div class="post-popup pst-pj">
    <div class="post-project">
        <h3>Post a project</h3>
        <div class="post-project-fields">
            <form>
                <div class="row">
                    <div class="col-lg-12">
                        <input type="text" name="title" placeholder="Title">
                    </div>
                    <div class="col-lg-12">
                        <div class="inp-field">
                            <select>
                                <option>Category</option>
                                <option>Category 1</option>
                                <option>Category 2</option>
                                <option>Category 3</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <input type="text" name="skills" placeholder="Skills">
                    </div>
                    <div class="col-lg-12">
                        <div class="price-sec">
                            <div class="price-br">
                                <input type="text" name="price1" placeholder="Price">
                                <i class="la la-dollar"></i>
                            </div>
                            <span>To</span>
                            <div class="price-br">
                                <input type="text" name="price1" placeholder="Price">
                                <i class="la la-dollar"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <textarea name="description" placeholder="Description"></textarea>
                    </div>
                    <div class="col-lg-12">
                        <ul>
                            <li><button class="active" type="submit" value="post">Post</button></li>
                            <li><a href="#" title="">Cancel</a></li>
                        </ul>
                    </div>
                </div>
            </form>
        </div><!--post-project-fields end-->
        <a href="#" title=""><i class="la la-times-circle-o"></i></a>
    </div><!--post-project end-->
</div><!--post-project-popup end-->

<div class="post-popup job_post">
    <div class="post-project">
        <h3>Post a job</h3>
        <div class="post-project-fields">
            <form>
                <div class="row">
                    <div class="col-lg-12">
                        <input type="text" name="title" placeholder="Title">
                    </div>
                    <div class="col-lg-12">
                        <div class="inp-field">
                            <select>
                                <option>Category</option>
                                <option>Category 1</option>
                                <option>Category 2</option>
                                <option>Category 3</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <input type="text" name="skills" placeholder="Skills">
                    </div>
                    <div class="col-lg-6">
                        <div class="price-br">
                            <input type="text" name="price1" placeholder="Price">
                            <i class="la la-dollar"></i>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="inp-field">
                            <select>
                                <option>Full Time</option>
                                <option>Half time</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <textarea name="description" placeholder="Description"></textarea>
                    </div>
                    <div class="col-lg-12">
                        <ul>
                            <li><button class="active" type="submit" value="post">Post</button></li>
                            <li><a href="#" title="">Cancel</a></li>
                        </ul>
                    </div>
                </div>
            </form>
        </div><!--post-project-fields end-->
        <a href="#" title=""><i class="la la-times-circle-o"></i></a>
    </div><!--post-project end-->
</div><!--post-project-popup end-->




<script>
    function NewPost() {
        $("#ShowModal").modal();

    }
</script>

<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/popper.js"></script>
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/jquery.mCustomScrollbar.js"></script>
<script type="text/javascript" src="lib/slick/slick.min.js"></script>
<script type="text/javascript" src="js/scrollbar.js"></script>
<script type="text/javascript" src="js/script.js"></script>

</body>