Social-Media/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Social_Media.Models;
using System.Net;

namespace Social_Media.Controllers
{

    public class PostController : Controller
    {

        private MyDbcontext _context;
        public PostController()
        {
            _context = new MyDbcontext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Post
        public ActionResult Index()
        {
            var post = _context.Posts.Include(p => p.User).ToList();
            return View(post);
        }
        public ActionResult FriendsPosts()
        {
            var post = _context.Posts.Include(p => p.User).ToList();
            return View(post);
        }

        public ActionResult Create(Post post)
        {
            var username = Session["Username"];
            User user1 = new User();
            user1 = _context.Users.Where(u => u.Username == username).FirstOrDefault();

            if (!ModelState.IsValid)
            {
                var posts = new Post();

                return View("Create", post);
            }

            if (post.ID == 0)

                post.like_post = 0;
            post.DateTime = DateTime.Now;
            post.UserID = (byte)user1.UserID;
            post.User = _context.Users.FirstOrDefault(user => user.UserID == post.UserID);
            post.DateTime = DateTime.Now;
            _context.Posts.Add(post);
            _context.SaveChanges();



            return RedirectToAction("Index", "Home");


        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var PostInDb = _context.Posts.Single(p => p.ID == id);
            if (PostInDb == null)
                return HttpNotFound();


            return View(PostInDb);

        }



        [HttpPost]
        public ActionResult Edit(Post post)
        {
            var PostInDb = _context.Posts.Single(p => p.ID == post.ID);

            if (ModelState.IsValid)
            {

                PostInDb.Body = post.Body;
                post.DateTime = DateTime.Now;
            }

            _context.SaveChanges();

            return RedirectToAction("Index", "Home");

        }

        public ActionResult AddEditPost(int? postId)
        {
            if (postId == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var PostInDb = _context.Posts.Single(p => p.ID == postId);
            if (PostInDb == null)
                return HttpNotFound();


            return View("Partial2", PostInDb);
        }

        [HttpPost]
        public ActionResult SaveData(Post post)
        {

            var username = Session["Username"];
            User user1 = new User();
            user1 = _context.Users.Where(u => u.Username == username).FirstOrDefault();

            try
            {
                MyDbcontext db = new MyDbcontext();


                if (post.ID > 0)
                {
                    //update
                    Post emp = db.Posts.SingleOrDefault(x => x.ID == post.ID);

                    emp.Body = post.Body;
                    emp.DateTime = DateTime.Now;
                    db.SaveChanges();


                }
                else
                {
                    //Insert
                    Post emp = new Post();
                    emp.UserID = (byte)user1.UserID;
                    emp.User = _context.Users.FirstOrDefault(user => user.UserID == emp.UserID);
                    emp.DateTime = DateTime.Now;
                    _context.Posts.Add(emp);
                    _context.SaveChanges();

                }
                return View(post);

            }
            catch (Exception ex)
            {

                throw ex;
            }

        }


        public ActionResult Delete(int? id)
        {
            var PostInDb = _context.Posts.Single(p => p.ID == id);
            if (PostInDb == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            _context.Posts.Remove(PostInDb);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }


        public ActionResult like(int id)
        {
            Post update = _context.Posts.ToList().Find(m => m.ID == id);
            update.like_post += 1;
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");

        }
    }


}

Social-Media/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
using Social_Media.Models;
using Social_Media.ViewModel;
namespace Social_Media.Controllers
{
    public class SearchController : Controller
    {
        const int Pending = 1;
        const int Blocked = 2;
        const int Accepted = 3;
        private MyDbcontext db = new MyDbcontext();
        [HttpGet]
        public ActionResult all(string search)
        {

            String namee = (String)Session["Username"];
            User login = db.Users.Where(x => x.Username.Equals(namee)).FirstOrDefault();
            ViewBag.Login = login.UserID;
            List<SearchableModel> serachList = new List<SearchableModel>();
            var result = db.Users.Where(x => x.Username.StartsWith(search)).ToList();

            foreach (var user in result)
            {
                int alreadFreiends = db.RelationShips.Where(x => ((x.Mate.UserID.Equals(login.UserID) && x.Friend.UserID == user.UserID) || (x.Friend.UserID.Equals(login.UserID)) && x.Mate.UserID == user.UserID) && x.Status == Accepted).Select(l => l.Status).SingleOrDefault();
                int CancelRequest = db.RelationShips.Where(x => x.ActionUser.UserID.Equals(login.UserID) && (x.Mate.UserID == user.UserID || x.Friend.UserID == user.UserID) && x.Status == Pending).Select(l => l.Status).FirstOrDefault();
                int PendingRequest = db.RelationShips.Where(x => x.ActionUser.UserID.Equals(user.UserID) && (x.Mate.UserID == login.UserID || x.Friend.UserID == login.UserID) && x.Status == Pending).Select(l => l.Status).FirstOrDefault();
                int block = db.RelationShips.Where(x => ((x.Mate.UserID.Equals(login.UserID) && x.Friend.UserID == user.UserID) || (x.Friend.UserID.Equals(login.UserID)) && x.Mate.UserID == user.UserID) && x.Status == Blocked).Select(l => l.Status).SingleOrDefault();

                if (PendingRequest == 1)
                    PendingRequest = 4;
                if (block == 0)
                    serachList.Add(new SearchableModel { ResultUser = user, RelationState = Math.Max(Math.Max(alreadFreiends, CancelRequest), PendingRequest) });
            }

            return View(serachList);
        }
        [HttpGet]
        public void AddFriend(int friendID)
        {
            String namee = (String)Session["Username"];
            User login = db.Users.Where(x => x.Username.Equals(namee)).FirstOrDefault();
            var mate = db.Users.Where(x => x.UserID.Equals(login.UserID)).Single();
            var friend = db.Users.Where(x => x.UserID.Equals(friendID)).Single();
            db.RelationShips.Add(new RelationShip { Mate = mate, Friend = friend, ActionUser = mate, Status = Pending });
            db.SaveChanges();

        }
        [HttpGet]
        public void CancelRequest(int friendID)
        {
            String namee = (String)Session["Username"];
            User login = db.Users.Where(x => x.Username.Equals(namee)).FirstOrDefault();
            int Relation = db.RelationShips.Where(x => ((x.Mate.UserID == friendID) && (x.Friend.UserID == login.UserID)) || ((x.Friend.UserID == friendID) && (x.Mate.UserID == login.UserID)))
                       .Select(l => l.RelationID).SingleOrDefault();
            db.RelationShips.Remove(db.RelationShips.Where(x => x.RelationID == Relation).Single());
            db.SaveChanges();
        }
        [HttpGet]
        public void AcceptFriendRequest(int friendID)
        {
            String namee = (String)Session["Username"];
            User login = db.Users.Where(x => x.Username.Equals(namee)).FirstOrDefault();
            int Relation = db.RelationShips.Where(x => ((x.Mate.UserID == friendID) && (x.Friend.UserID == login.UserID)) || ((x.Friend.UserID == friendID) && (x.Mate.UserID == login.UserID)))
                       .Select(l => l.RelationID).SingleOrDefault();
            RelationShip update = new RelationShip();
            update = db.RelationShips.Where(x => x.RelationID == Relation).Single();
            update.Status = 3;
            db.RelationShips.Attach(update);
            db.Entry(update).Property(x => x.Status).IsModified = true;
            db.SaveChanges();
        }
        [HttpGet]
        public JsonResult friendrequests()
        {
            String namee = (String)Session["Username"];
            User login = db.Users.Where(x => x.Username.Equals(namee)).FirstOrDefault();
            var FirstPendingRequest = db.RelationShips.Where(x => x.ActionUser.UserID != login.UserID && x.Mate.UserID == login.UserID && x.Status == 1).Select(
                x => new
                {
                    name = x.Friend.Username,
                    id = x.Friend.UserID,
                    img = x.Friend.Pic,
                }).ToList();
            var SecPendingRequest = db.RelationShips.Where(x => x.ActionUser.UserID != login.UserID && x.Friend.UserID == login.UserID && x.Status == 1).Select(
                x => new
                {
                    name = x.Mate.Username,
                    id = x.Mate.UserID,
                    img = x.Mate.Pic,
                }
                ).ToList();
            foreach (var user in SecPendingRequest)
                FirstPendingRequest.Add(user);

            return Json(FirstPendingRequest, JsonRequestBehavior.AllowGet);
        }

    }
}

Social-Media/Views/Shared/Edit.cshtml
@model Social_Media.Models.Post
    @{ 
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "Post"))
{
    @Html.HiddenFor(m => m.ID)

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

Social-Media/Views/Shared/FriendsPosts.cshtml
@model IEnumerable<Social_Media.Models.Post>




    <section id="deletePosts" class="forum-page">
        @foreach (var post in Model)
        {
            <div class="posts-section">
                <div class="post-bar">
                    <div class="post_topbar">
                        <div class="usy-dt">
                            <img src="http://via.placeholder.com/50x50" alt="">
                            <div class="usy-name">
                                <h3>@post.User.Username</h3>
                                <span><img src="/Content/images/clock.png" alt="">@post.DateTime</span>
                            </div>
                        </div>
                        <div class="ed-opts">
                            <a href="#" title="" class="ed-opts-open"><i class="la la-ellipsis-v"></i></a>
                            <ul class="ed-options">
                                <li><a onclick="AddEditPost(@post.ID)" href="#" title="">Edit Post</a></li>
                                <li><a data-customer-id="@post.ID" class="js-delete" href="#" title="">Delete</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="job_descp">


                        <p>@post.Body</p>
                    </div>
                    <div class="job-status-bar">
                        <ul class="like-com">
                            <img src="/Content/images/liked-img.png" alt="">
                            <li>@Html.DisplayFor(modelItem => post.like_post)<i class="la la-heart"></i>like <br /></li>
                            <li>@Html.ActionLink("Like", "like", "Post", new { id = @post.ID }, null)</li>
                        </ul>
                        <div class="comment-st">
                            <ul>
                                <li><a class="com" href="#" title="" onclick="NewComment()"> <img src="images/com.png" alt=""> Comment </a> </li>

                            </ul>
                        </div><!--post-st end-->

                    </div>
                </div><!--post-bar end-->

            </div>
        }
    </section>

Social-Media/Views/Shared/Index.cshtml
@model IEnumerable<Social_Media.ViewModel.CommentsModel>
@using Social_Media.Models

@{
    ViewBag.Title = "PostIndex";
    MyDbcontext db = new MyDbcontext();
    var username = Session["Username"];
    User user = new User();
    user = db.Users.Where(u => u.Username == username).FirstOrDefault();
}

<!DOCTYPE html>
<html>

<body>



    <div class="wrapper">







        <section id="deletePosts" class="forum-page">
            @foreach (var post in Model)
            {
                <div class="posts-section">
                    <div class="post-bar">
                        <div class="post_topbar">
                            <div class="usy-dt">
                                @if (post.post.User.Pic == null)
                                {
                                    <img src="http://via.placeholder.com/50x50" alt="">
                                }
                                else
                                {
                                    <img src="~/UploadedFiles/@Html.DisplayFor(model=>post.post.User.Pic)" alt="" style="width:50px;height:50px">
                                }
                                <div class="usy-name">
                                    <h3>@post.post.User.Username </h3>
                                    <span><img src="/Content/images/clock.png" alt="">@post.post.DateTime</span>
                                </div>
                            </div>
                            @if(post.post.UserID==user.UserID)
                            {
                                <div class="ed-opts">
                                    <a href="#" title="" class="ed-opts-open"><i class="la la-ellipsis-v"></i></a>
                                    <ul class="ed-options">
                                        <li><a onclick="AddEditPost(@post.post.ID)" href="#" title="">Edit Post</a></li>
                                        <li><a data-customer-id="@post.post.ID" class="js-delete" href="#" title="">Delete</a></li>
                                    </ul>
                                </div>
                            }
                        </div>
                        <div class="job_descp">


                            <p>@post.post.Body</p>
                        </div>
                        <div class="job-status-bar">
                            <ul class="like-com">
                                <img src="/Content/images/liked-img.png" alt="">
                                <li>@Html.DisplayFor(modelItem => post.post.like_post)<i class="la la-heart"></i>like <br /></li>
                                <li>@Html.ActionLink("Like", "like", "Post", new { id = @post.post.ID }, null)</li>
                            </ul>
                            <div class="comment-st">
                                <ul>
                                    <li><a class="com" href="#" title="" data-arg1="@post.post.ID" onclick="NewComment()"> <img src="images/com.png" alt=""> Comment </a> </li>

                                </ul>
                                <table class="table table-striped">
                                    @foreach (var com in post.Comments)
                                    {
                                        <tr style="color:#FA8072 ; border: 2px solid #F5B041  ;border-radius: 20px; ">
                                            <td>
                                                <h3>@com.Content</h3>
                                            </td>
                                        </tr>
                                    }
                                </table>

                            </div><!--post-st end-->
                        </div>
                    </div><!--post-bar end-->

                </div>
            }
        </section>

    </div>

    <div class="modal fade" id="myModal1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h3 class="modal-title">AddEdit Post</h3>
                </div>
                <div class="modal-body" id="myModalBodyDiv1">


                </div>


            </div>

        </div>

    </div>
    <button style="display : none" id="omaragamy"></button>
    <div class="modal fade" id="ShowComment">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h4>New Comment</h4>
                </div>
                <div class="modal-body">
                    <form id="comment">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                <input class="form-control" type="text" name="Content" id="content" placeholder="Your Comment ..." />
                            </div>
                        </div>



                    </form>
                    <div class="form-group">

                        <button class="btn btn-info form-control" type="submit" onclick="SaveComment()"><i class="glyphicon glyphicon-registration-mark"></i> Comment</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
<script>

    var AddEditPost = function (postId) {

        var url = "/Post/AddEditPost?postId=" + postId;

        $("#myModalBodyDiv1").load(url, function () {
            $("#myModal1").modal("show");

        })

    }


    function SaveForm() {


        var Body = $("#body").val();

        if (Body == "") {

            return false;
        }
        var data = $("#post").serialize();
        $.ajax({
            type: "post",
            data: data,
            url: "/Post/Create",
            success: function (result) {


                // $("#post")[0].reset();

                window.location.reload(true);

            }
        });
    }
    function NewComment() {
        var postid = event.target.getAttribute('data-arg1');

        var button = document.getElementById('omaragamy');
        button.innerHTML = postid;

        $("#ShowComment").modal();

    }
    function SaveComment() {
        var button1 = document.getElementById('omaragamy');
        //alert(button1.innerHTML);
        var Content = $("#content").val();
        if (Content == "") {

            return false;
        }
        var data = $("#comment").serialize();
        $.ajax({
            type: "GET",
            url: "/Comment/AddComment/" + button1.innerHTML + "?str=" + data,
            success: function (result) {


                // $("#comment")[0].reset();

                window.location.reload(true);

            }
        });
    }
    $(document).ready(function () {
        $("#deletePosts .js-delete").click(function () {
            var button = $(this);
            bootbox.confirm("Are You Sure To Delete", function (result) {
                if (result) {
                    $.ajax({
                        url: "/Post/Delete/" + button.attr("data-customer-id"),
                        method: "POST",
                        success: function () {

                            $("#deletePosts").remove();
                            window.location.reload(true);

                        }
                    });

                }
            });
        });
    });
    $("#BtnLike").click(function () {

        var button = $(this);

        $.ajax({
            url: "/Post/like/" + button.attr("data-like-id"),
            data: data,
            cache: false,
            type: "POST",
            success: function (result) {
                window.location.reload(true);
            },
            error: function (result) {
                alert("failed");
            }
        });
    });


</script>

Social-Media/Views/Shared/New.cshtml
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New</h2>

Social-Media/Views/Shared/Partial2.cshtml
@model Social_Media.Models.Post



<div>

    <form id="myForm">
        @Html.HiddenFor(m => m.ID)

       

        @Html.TextBoxFor(model => model.Body, new { @class = "form-control", @placeholder = "Your Post" })

        <a href="#" id="btnSubmit" class="btn btn-success btn-block">@if (Model.ID > 0)
        {<span>Update</span> }
        else
        {<span>Save</span>} </a>

    </form>

    

</div>


<script>

    $(document).ready(function () {

        $("#btnSubmit").click(function () {

            

            var myformdata = $("#myForm").serialize();

            $.ajax({

                type: "POST",
                url: "/Post/SaveData",
                data: myformdata,
                success: function () {
                   
                    $("#myModal1").modal("hide");
                    window.location.reload(true);

                }

            })
        })

    })

    $(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});

  


</script>

Social-Media/Views/Shared/SaveData.cshtml
@{
    ViewBag.Title = "SaveData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SaveData</h2>

Social-Media/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <body>
        @RenderBody()
        

    </body>
</html>